todo/models.py
from random import random
import uuid
from flask import Flask, jsonify, request
from db import Database

class Task:
    def __init__(self):
        self.todo_db = Database().get_database()

    def create(self):
        # print(request.form)
        task = {
            "name": request.form.get('taskname'),
            "user_id": ""
        }

        # task = {
        #     "name": "task" + uuid.uuid4().hex,
        #     "user_id": ""
        # }

        # check for existing task
        try: 
            self.todo_db.tasks.insert_one(task)
        except:
            return {'error': 'Cannot delete.'}
        else:
            return {'error': 'Cannot delete.'}

        return {'error': 'Cannot delete.'}
        
    def update(self):
        update_task_name = request.form.get('taskname')
        if update_task_name:
            try:
                self.todo_db.tasks.update_one({'name':request.form.get('oldname')}, {'$set': {'name': update_task_name}})
                return self.get_one(update_task_name)
            except:
                return {'error': 'cannot update'}
        else:
            return {'error': 'cannot update'}
    
    def delete(self, name):
        task_exist = self.task_exist(name)

        if task_exist:
            try:
                self.todo_db.tasks.delete_one({'name': name})
            except:
                return {'error': 'Cannot delete.'}
            else:
                return {'error': 'Cannot delete.'}
            
        return {'error': 'Cannot delete.'}

    def get_all(self):
            all_tasks = self.todo_db.tasks.find({})
            if all_tasks:
                return list(all_tasks)
            else:
                return {'error': 'No tasks available'}
    
    def get_one(self, name):
        task = list(self.todo_db.tasks.find({'name': name}))

        if len(list(task)) > 0:
            return (list(task))[0]
        return {'error': 'No task found'}
    
    def task_exist(self, name):
        task_exist = self.get_one(name)

        if 'error' in task_exist:
            return False
        return True
            

__init__.py
import os
from .blog import create

from flask import Flask
from . import db

def create_app(test_config=None):
    # create and configure the app
    app = Flask(__name__, instance_relative_config=True)
    app.config.from_mapping(
        SECRET_KEY='dev',
        DATABASE=os.path.join(app.instance_path, 'flaskwokshop.sqlite'),
    )
    db.init_app(app)

    if test_config is None:
        # load the instance config, if it exists, when not testing
        app.config.from_pyfile('config.py', silent=True)
    else:
        # load the test config if passed in
        app.config.from_mapping(test_config)

    # ensure the instance folder exists
    try:
        os.makedirs(app.instance_path)
    except OSError:
        pass

    # a simple page that says hello
    @app.route('/hello')
    def hello():
        return 'Hello, World!'

    
    # if __name__ == "__main__":
    #     port = int(os.environ.get('PORT', 3000))
    #     app.run(debug=True, host='0.0.0.0', port=port)

    from . import auth
    app.register_blueprint(auth.bp)

    from . import blog
    app.register_blueprint(blog.bp)
    app.add_url_rule('/', endpoint='index')

    return app

app.py
from flask import Flask, render_template
import os

app = Flask(__name__)

@app.route('/')
def home():
    return render_template('index.html')

@app.route("/heaven")
def hello_heaven():
    return "<p>Hello from the Heaven</p>"

if __name__ == "__main__":
    port = int(os.environ.get('PORT', 3000))
    app.run(debug=True, host='0.0.0.0', port=port)

auth.py
import functools

from flask import (
    Blueprint, flash, g, redirect, render_template, request, session, url_for
)
from werkzeug.security import check_password_hash, generate_password_hash

from flask_lab.db import get_db

bp = Blueprint('auth', __name__, url_prefix='/auth')

@bp.route('/register', methods=('GET', 'POST'))
def register():
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']
        db = get_db()
        error = None

        if not username:
            error = 'Username is required.'
        elif not password:
            error = 'Password is required.'

        if error is None:
            try:
                db.execute(
                    "INSERT INTO user (username, password) VALUES (?, ?)",
                    (username, generate_password_hash(password)),
                )
                db.commit()
            except db.IntegrityError:
                error = f"User {username} is already registered."
            else:
                return redirect(url_for("auth.login"))

        flash(error)

    return render_template('auth/register.html')

@bp.route('/login', methods=('GET', 'POST'))
def login():
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']
        db = get_db()
        error = None
        user = db.execute(
            'SELECT * FROM user WHERE username = ?', (username,)
        ).fetchone()

        if user is None:
            error = 'Incorrect username.'
        elif not check_password_hash(user['password'], password):
            error = 'Incorrect password.'

        if error is None:
            session.clear()
            session['user_id'] = user['id']
            return redirect(url_for('index'))

        flash(error)

    return render_template('auth/login.html')

@bp.before_app_request
def load_logged_in_user():
    user_id = session.get('user_id')

    if user_id is None:
        g.user = None
    else:
        g.user = get_db().execute(
            'SELECT * FROM user WHERE id = ?', (user_id,)
        ).fetchone()

@bp.route('/logout')
def logout():
    session.clear()
    return redirect(url_for('index'))

def login_required(view):
    @functools.wraps(view)
    def wrapped_view(**kwargs):
        if g.user is None:
            return redirect(url_for('auth.login'))

        return view(**kwargs)

    return wrapped_view

todo/routes.py
from flask import Flask, Blueprint, render_template, url_for, json, request, redirect
from todo.models import Task

bp = Blueprint('todo', __name__)

@bp.route('/')
def index():
    all_tasks = Task().get_all()
    return render_template('todo/index.html', tasks = all_tasks)

@bp.route('/create', methods=['GET', 'POST'])
def create():
    if request.method == 'POST':
        new_task = Task().create()
        return redirect(url_for('todo.index'))

    return render_template('todo/create.html')
    


@bp.route('/update/<name>', methods=['GET', 'POST'])
def update(name):
    task = Task().get_one(name)
    
    if request.method == 'POST':
        task = Task().update()
        return redirect(url_for('todo.index'))
        
    return render_template('todo/update.html', task = task)

@bp.route('/delete/<name>', methods=['POST'])
def delete(name):
    delete = Task().delete(name)
    return redirect(url_for('todo.index'))

    

templates/base.html
<!DOCTYPE html>
<html lang="en">
<!-- <meta name="viewport" content="width=device-width, initial-scale=1"> -->

<title>
    {%block title%} {%endblock%} - Python - Flask - Docker - Workshop
</title>

<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
<link rel="stylesheet" href="{{ url_for('static', filename='style.css')}}">

<nav class="navbar navbar-default bg-primary">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="#">Python - Flask - Docker - Workshop</a>
        </div>
        <ul class="nav navbar-nav">
            <li class=""><a href="{{url_for('todo.index')}}">Task Lists</a></li>

        </ul>
    </div>
</nav>


<div class="container">
    {%block body%} {%endblock%}
</div>

<!-- jQuery library -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

<!-- Latest compiled JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

templates/blog/create.html
{% extends 'base.html' %}

{% block header %}
  <h1>{% block title %}New Post{% endblock %}</h1>
{% endblock %}

{% block content %}
  <form method="post">
    <label for="title">Title</label>
    <input name="title" id="title" value="{{ request.form['title'] }}" required>
    <label for="body">Body</label>
    <textarea name="body" id="body">{{ request.form['body'] }}</textarea>
    <input type="submit" value="Save">
  </form>
{% endblock %}

templates/blog/index.html
{% extends 'base.html' %}

{% block header %}
  <h1>{% block title %}Posts{% endblock %}</h1>
  {% if g.user %}
    <a class="action" href="{{ url_for('blog.create') }}">New</a>
  {% endif %}
{% endblock %}

{% block content %}
  {% for post in posts %}
    <article class="post">
      <header>
        <div>
          <h1>{{ post['title'] }}</h1>
          <div class="about">by {{ post['username'] }} on {{ post['created'].strftime('%Y-%m-%d') }}</div>
        </div>
        {% if g.user['id'] == post['author_id'] %}
          <a class="action" href="{{ url_for('blog.update', id=post['id']) }}">Edit</a>
        {% endif %}
      </header>
      <p class="body">{{ post['body'] }}</p>
    </article>
    {% if not loop.last %}
      <hr>
    {% endif %}
  {% endfor %}
{% endblock %}

templates/blog/update.html
{% extends 'base.html' %}

{% block header %}
  <h1>{% block title %}Edit "{{ post['title'] }}"{% endblock %}</h1>
{% endblock %}

{% block content %}
  <form method="post">
    <label for="title">Title</label>
    <input name="title" id="title"
      value="{{ request.form['title'] or post['title'] }}" required>
    <label for="body">Body</label>
    <textarea name="body" id="body">{{ request.form['body'] or post['body'] }}</textarea>
    <input type="submit" value="Save">
  </form>
  <hr>
  <form action="{{ url_for('blog.delete', id=post['id']) }}" method="post">
    <input class="danger" type="submit" value="Delete" onclick="return confirm('Are you sure?');">
  </form>
{% endblock %}

templates/index.html
<!DOCTYPE html>

<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Python - Flask - Workshop - Docker</title>
</head>

<body>
    <h2>
        Congratulations!!! You successfully ran a flask application.
    </h2>
</body>

</html>

templates/todo/create.html
{%extends 'base.html' %}
<section>
    {%block title %} Add {%endblock%} {%block body%}
    <form method="post">
        <div class="form-group">
            <label for="taskname">Task Name</label>
            <input type="text" name="taskname" class="form-control" id="taskname">
        </div>
        <button type="submit" class="btn btn-primary">Add</button>
    </form>
</section>
{%endblock%}

templates/todo/index.html
{%extends 'base.html' %} {%block body%}

<div class="title relative">
    Tasks
    <a class="position-end btn btn-default" href="{{url_for('todo.create')}}">Add</button>
</div>
<div class="list-group">
    {% for task in tasks %}
    <a href="/update/{{task['name']}}" class="list-group-item list-group-item-action">
        {{task['name']}}
    </a> {%endfor%}
</div>
{%endblock%}

templates/todo/update.html
{%extends 'base.html' %}
<section>
    {%block title %} {{task['name']}} - Update {%endblock%} {%block body%} {% if task['error'] %}
    <div class="alert alert-danger" role="alert">
        {{task['error']}}
    </div>
    {% else %}
    <form method="post">
        <div class="form-group">
            <input type="text" name="oldname" value="{{task['name']}}" hidden>
            <label for="taskname">Task Name</label>
            <input type="text" name="taskname" class="form-control" id="taskname" value="{{request.form['name'] or task['name']}}" placeholder="{{request.form['name'] or task['name']}}">
        </div>
        <button type="submit" class="btn btn-primary">Update</button>
    </form>
    <form action="{{ url_for('todo.delete', name=task['name']) }}" method="post">
        <input class="btn btn-danger" type="submit" value="Delete" onclick="return confirm('Are you sure?');">
    </form>
    {% endif %}
</section>
{%endblock%}